"""
Report Generator Service — AI-generated weekly reports for ward officers.
Compiles complaint data, resolution rates, citizen feedback into structured reports.
"""

from datetime import datetime, timedelta
from typing import Dict, List, Optional
from sqlalchemy.orm import Session
from sqlalchemy import func
from models.complaint import Complaint, ComplaintStatus, PriorityLevel


class ReportService:
    def generate_ward_report(
        self,
        db: Session,
        ward: str,
        date_from: Optional[str] = None,
        date_to: Optional[str] = None,
    ) -> Dict:
        """Generate a comprehensive weekly report for a ward."""

        # Default to last 7 days
        if date_to:
            end_date = datetime.fromisoformat(date_to)
        else:
            end_date = datetime.now()

        if date_from:
            start_date = datetime.fromisoformat(date_from)
        else:
            start_date = end_date - timedelta(days=7)

        period = f"{start_date.strftime('%b %d')} — {end_date.strftime('%b %d, %Y')}"

        # Query complaints in the period
        complaints = (
            db.query(Complaint)
            .filter(Complaint.ward == ward)
            .filter(Complaint.created_at >= start_date)
            .filter(Complaint.created_at <= end_date)
            .all()
        )

        total = len(complaints)
        resolved = len([c for c in complaints if c.status == ComplaintStatus.RESOLVED])
        in_progress = len([c for c in complaints if c.status == ComplaintStatus.IN_PROGRESS])
        open_count = len([c for c in complaints if c.status == ComplaintStatus.OPEN])
        p0_count = len([c for c in complaints if c.priority == PriorityLevel.P0])
        p1_count = len([c for c in complaints if c.priority == PriorityLevel.P1])

        # Average rating
        rated = [c for c in complaints if c.rating is not None]
        avg_rating = sum(c.rating for c in rated) / len(rated) if rated else 0.0

        # Resolution time
        resolved_complaints = [c for c in complaints if c.resolved_at and c.created_at]
        if resolved_complaints:
            avg_hours = sum(
                (c.resolved_at - c.created_at).total_seconds() / 3600
                for c in resolved_complaints
            ) / len(resolved_complaints)
        else:
            avg_hours = 0.0

        # Category breakdown
        categories: Dict[str, int] = {}
        for c in complaints:
            categories[c.category] = categories.get(c.category, 0) + 1

        # Build report
        stats = {
            "total": total,
            "resolved": resolved,
            "in_progress": in_progress,
            "open": open_count,
            "p0_critical": p0_count,
            "p1_high": p1_count,
            "resolution_rate": round((resolved / total * 100) if total > 0 else 0, 1),
            "avg_rating": round(avg_rating, 1),
            "avg_resolution_hours": round(avg_hours, 1),
            "category_breakdown": categories,
        }

        report_text = self._format_report(ward, period, stats)

        return {
            "report_text": report_text,
            "ward": ward,
            "period": period,
            "stats": stats,
        }

    def _format_report(self, ward: str, period: str, stats: Dict) -> str:
        """Format the report as structured text."""
        lines = [
            "━" * 48,
            f"  WEEKLY WARD REPORT — {ward}",
            f"  Period: {period}",
            "━" * 48,
            "",
            f"  Total Complaints:      {stats['total']}",
            f"  Resolved:              {stats['resolved']} ({stats['resolution_rate']}%)",
            f"  In Progress:           {stats['in_progress']}",
            f"  Open / Pending:        {stats['open']}",
            "",
            f"  P0 Critical Issues:    {stats['p0_critical']}",
            f"  P1 High Priority:      {stats['p1_high']}",
            "",
            f"  Citizen Satisfaction:   {stats['avg_rating']} / 5.0",
            f"  Avg Resolution Time:   {stats['avg_resolution_hours']} hours",
            "",
            "  CATEGORY BREAKDOWN:",
        ]

        for cat, count in sorted(stats["category_breakdown"].items(), key=lambda x: -x[1]):
            pct = round(count / stats["total"] * 100) if stats["total"] > 0 else 0
            lines.append(f"    {cat}: {count} ({pct}%)")

        lines.extend([
            "",
            "━" * 48,
            "  Generated by JanShakti.AI Report Engine",
            "━" * 48,
        ])

        return "\n".join(lines)

    def generate_fallback_report(self, ward: str) -> Dict:
        """Generate a demo report when no DB data is available."""
        stats = {
            "total": 46,
            "resolved": 23,
            "in_progress": 8,
            "open": 15,
            "p0_critical": 2,
            "p1_high": 5,
            "resolution_rate": 50.0,
            "avg_rating": 4.2,
            "avg_resolution_hours": 55.2,
            "category_breakdown": {
                "Water Supply": 14,
                "Roads & Potholes": 10,
                "Drainage": 7,
                "Electricity": 6,
                "Garbage & Sanitation": 5,
                "Others": 4,
            },
        }

        period = f"{(datetime.now() - timedelta(days=7)).strftime('%b %d')} — {datetime.now().strftime('%b %d, %Y')}"
        report_text = self._format_report(ward, period, stats)

        return {
            "report_text": report_text,
            "ward": ward,
            "period": period,
            "stats": stats,
        }


# Singleton
report_service = ReportService()
